name: ns_player
description: NSPlayer is a HLS(.m3u8) video player for flutter. The NsPlayer is a video player that allows you to select HLS video streaming by selecting the quality.
version: 0.0.1+2
homepage: https://github.com/Nurullah-Sadekin/ns_player/blob/main/example/lib/main.dart
repository: https://github.com/Nurullah-Sadekin/ns_player

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.1.4
  video_player: ^2.9.1
  wakelock_plus: ^1.2.8
  path: ^1.9.0
  flutter_lints: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter